/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.GymMember;

/**
 *
 * @author yuujadz
 */
public class memberPanel extends javax.swing.JPanel {

    /**
     * Creates new form memberPanel
     */
    public memberPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestManager = new javax.swing.JButton();
        btnViewPayment = new javax.swing.JButton();
        btnBookCardioClass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBookPersonalTraining = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequestManager.setText("Request My Manager");
        btnRequestManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManagerActionPerformed(evt);
            }
        });
        add(btnRequestManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 40));

        btnViewPayment.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnViewPayment.setText("Pending Membership Payments");
        btnViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPaymentActionPerformed(evt);
            }
        });
        add(btnViewPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 40));

        btnBookCardioClass.setText("Book a Cardio Class");
        btnBookCardioClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookCardioClassActionPerformed(evt);
            }
        });
        add(btnBookCardioClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBookPersonalTraining.setText("Book a Personal Trainer");
        btnBookPersonalTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookPersonalTrainingActionPerformed(evt);
            }
        });
        add(btnBookPersonalTraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestManagerActionPerformed

    private void btnBookCardioClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookCardioClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookCardioClassActionPerformed

    private void btnViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPaymentActionPerformed

    private void btnBookPersonalTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookPersonalTrainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookPersonalTrainingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookCardioClass;
    private javax.swing.JButton btnBookPersonalTraining;
    private javax.swing.JButton btnRequestManager;
    private javax.swing.JButton btnViewPayment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
