/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Basic;

/**
 *
 * @author yuujadz
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegisterAsCoach = new javax.swing.JButton();
        rbtnPersonalTrainer = new javax.swing.JRadioButton();
        rbtnCardioCoach = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtnPersonalTrainer1 = new javax.swing.JRadioButton();
        rbtnCardioCoach1 = new javax.swing.JRadioButton();
        rbtnPersonalTrainer2 = new javax.swing.JRadioButton();
        txtAge = new javax.swing.JTextField();
        txtUsername1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JTextField();
        btnLogIn1 = new javax.swing.JButton();
        btnRegisterAsMember = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("or");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel2.setText("Register As Member");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setText("Register As Coach");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnRegisterAsCoach.setText("Register");
        btnRegisterAsCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAsCoachActionPerformed(evt);
            }
        });
        add(btnRegisterAsCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        rbtnPersonalTrainer.setText("Personal Trainer");
        rbtnPersonalTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPersonalTrainerActionPerformed(evt);
            }
        });
        add(rbtnPersonalTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        rbtnCardioCoach.setText("Cardio Coach");
        rbtnCardioCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCardioCoachActionPerformed(evt);
            }
        });
        add(rbtnCardioCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel5.setText("User Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel8.setText("Gender");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, 20));

        rbtnPersonalTrainer1.setText("Non-Binary");
        rbtnPersonalTrainer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPersonalTrainer1ActionPerformed(evt);
            }
        });
        add(rbtnPersonalTrainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        rbtnCardioCoach1.setText("Female");
        rbtnCardioCoach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCardioCoach1ActionPerformed(evt);
            }
        });
        add(rbtnCardioCoach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        rbtnPersonalTrainer2.setText("Male");
        rbtnPersonalTrainer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPersonalTrainer2ActionPerformed(evt);
            }
        });
        add(rbtnPersonalTrainer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, 30));

        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });
        add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 180, 30));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 180, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 180, 30));

        jLabel9.setText("User Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel10.setText("Password");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        txtUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername2ActionPerformed(evt);
            }
        });
        add(txtUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 180, 30));

        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });
        add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 180, 30));

        btnLogIn1.setText("Log In");
        add(btnLogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        btnRegisterAsMember.setText("Register");
        add(btnRegisterAsMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnPersonalTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPersonalTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPersonalTrainerActionPerformed

    private void rbtnCardioCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCardioCoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCardioCoachActionPerformed

    private void rbtnPersonalTrainer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPersonalTrainer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPersonalTrainer1ActionPerformed

    private void rbtnCardioCoach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCardioCoach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCardioCoach1ActionPerformed

    private void rbtnPersonalTrainer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPersonalTrainer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPersonalTrainer2ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername2ActionPerformed

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void btnRegisterAsCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAsCoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterAsCoachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JButton btnRegisterAsCoach;
    private javax.swing.JButton btnRegisterAsMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnCardioCoach;
    private javax.swing.JRadioButton rbtnCardioCoach1;
    private javax.swing.JRadioButton rbtnPersonalTrainer;
    private javax.swing.JRadioButton rbtnPersonalTrainer1;
    private javax.swing.JRadioButton rbtnPersonalTrainer2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsername2;
    // End of variables declaration//GEN-END:variables
}
