/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Accountant;

import ui.CoachManager.*;

/**
 *
 * @author yuujadz
 */
public class AccountantPanel extends javax.swing.JPanel {

    /**
     * Creates new form coachManagerPanel
     */
    public AccountantPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewCoachRequest = new javax.swing.JButton();
        btnViewDashboard = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewCoachRequest.setText("Request Payment");
        btnNewCoachRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCoachRequestActionPerformed(evt);
            }
        });
        add(btnNewCoachRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 40));

        btnViewDashboard.setText("View Dashboard");
        btnViewDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDashboardActionPerformed(evt);
            }
        });
        add(btnViewDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCoachRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCoachRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewCoachRequestActionPerformed

    private void btnViewDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewCoachRequest;
    private javax.swing.JButton btnViewDashboard;
    // End of variables declaration//GEN-END:variables
}
