/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FittnessTester;

import ui.GymMember.*;
import javax.swing.JPanel;
import model.Enterprise.MemberEnterprise;
import model.Enterprise.PhysicalTherapistEnterprise;
import model.Network.Network;
import model.Organization.PhisicalCheckOrganization;
import model.Organization.WelcomingOrganization;
import model.System.EcoSystem;
import model.UserAccount.UserAccount;

/**
 *
 * @author yuujadz
 */
public class TesterPanel extends javax.swing.JPanel {

    /**
     * Creates new form memberPanel
     */
    public TesterPanel() {
        initComponents();
    }

    public TesterPanel(JPanel userProcessContainer, UserAccount account, PhisicalCheckOrganization phisicalCheckOrganization, PhysicalTherapistEnterprise physicalTherapistEnterprise, Network network, EcoSystem ecosystem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestManager = new javax.swing.JButton();
        btnViewPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRequestPersonalTrainer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequestManager.setText("My Information");
        btnRequestManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManagerActionPerformed(evt);
            }
        });
        add(btnRequestManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 40));

        btnViewPayment.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnViewPayment.setText("Pending Membership Payments");
        btnViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPaymentActionPerformed(evt);
            }
        });
        add(btnViewPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRequestPersonalTrainer.setText("Request Personal Trainer");
        btnRequestPersonalTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestPersonalTrainerActionPerformed(evt);
            }
        });
        add(btnRequestPersonalTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Member Panel");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestManagerActionPerformed

    private void btnViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPaymentActionPerformed

    private void btnRequestPersonalTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestPersonalTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestPersonalTrainerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestManager;
    private javax.swing.JButton btnRequestPersonalTrainer;
    private javax.swing.JButton btnViewPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
