/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CoachManager;

/**
 *
 * @author yuujadz
 */
public class coachManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form coachManagerPanel
     */
    public coachManagerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewCoachRequest = new javax.swing.JButton();
        btnViewCoach = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewCoachRequest.setText("New Coach Applicant");
        btnNewCoachRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCoachRequestActionPerformed(evt);
            }
        });
        add(btnNewCoachRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 40));

        btnViewCoach.setText("View Coach");
        btnViewCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoachActionPerformed(evt);
            }
        });
        add(btnViewCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCoachRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCoachRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewCoachRequestActionPerformed

    private void btnViewCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCoachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewCoachRequest;
    private javax.swing.JButton btnViewCoach;
    // End of variables declaration//GEN-END:variables
}
