/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FittnessConsultant;

import javax.swing.JPanel;
import model.Enterprise.PhysicalTherapistEnterprise;
import model.Network.Network;
import model.Organization.PhisicalCheckOrganization;
import model.System.EcoSystem;
import model.UserAccount.UserAccount;
import ui.GymManager.*;
import ui.GymMember.*;

/**
 *
 * @author yuujadz
 */
public class fittnessConsultantPanel extends javax.swing.JPanel {

    /**
     * Creates new form memberPanel
     */
    public fittnessConsultantPanel() {
        initComponents();
    }

    public fittnessConsultantPanel(JPanel userProcessContainer, UserAccount account, PhisicalCheckOrganization phisicalCheckOrganization, PhysicalTherapistEnterprise physicalTherapistEnterprise, Network network, EcoSystem ecosystem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewConsultRequest = new javax.swing.JButton();
        btnViewMyMember = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewConsultRequest.setText("View Consult Requests");
        btnViewConsultRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewConsultRequestActionPerformed(evt);
            }
        });
        add(btnViewConsultRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 40));

        btnViewMyMember.setText("View My Member");
        btnViewMyMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyMemberActionPerformed(evt);
            }
        });
        add(btnViewMyMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewConsultRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewConsultRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewConsultRequestActionPerformed

    private void btnViewMyMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMyMemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewConsultRequest;
    private javax.swing.JButton btnViewMyMember;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
