/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FittnessConsultant;

import ui.GymManager.*;

/**
 *
 * @author yuujadz
 */
public class myMemebers extends javax.swing.JPanel {

    /**
     * Creates new form managmentRequest
     */
    public myMemebers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagerRequests = new javax.swing.JTable();
        btnRequestBodyTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblManagerRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblManagerRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 320));

        btnRequestBodyTest.setText("Request Body Test");
        btnRequestBodyTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBodyTestActionPerformed(evt);
            }
        });
        add(btnRequestBodyTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("My Members");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestBodyTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBodyTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestBodyTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestBodyTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManagerRequests;
    // End of variables declaration//GEN-END:variables
}
