/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

/**
 *
 * @author yuujadz
 */
public class manageRoles extends javax.swing.JPanel {

    /**
     * Creates new form manageOrganization
     */
    public manageRoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnCreateRole = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuNetwork = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        menuEnterprise = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        menuOrg = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Enterprise", "Organization"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 600, 230));

        jLabel1.setText("Select Network: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 210, 40));

        btnCreateRole.setText("Add");
        add(btnCreateRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel2.setText("New Organization Name: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        menuNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNetworkActionPerformed(evt);
            }
        });
        add(menuNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 210, -1));

        jLabel3.setText("Select Enterprise: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 20));

        menuEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnterpriseActionPerformed(evt);
            }
        });
        add(menuEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 210, -1));

        jLabel4.setText("Select Organization: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 20));

        menuOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrgActionPerformed(evt);
            }
        });
        add(menuOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void menuNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNetworkActionPerformed

    private void menuEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEnterpriseActionPerformed

    private void menuOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> menuEnterprise;
    private javax.swing.JComboBox<String> menuNetwork;
    private javax.swing.JComboBox<String> menuOrg;
    // End of variables declaration//GEN-END:variables
}
