/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import javax.swing.JPanel;
import model.System.EcoSystem;
import model.UserAccount.UserAccount;

/**
 *
 * @author yuujadz
 */
public class ManageAccount extends javax.swing.JPanel {

    /**
     * Creates new form manageOrganization
     */
    public ManageAccount() {
        initComponents();
    }

    ManageAccount(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreateOrg = new javax.swing.JButton();
        menuNetwork = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        menuOrganization = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        menuEnterprise = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Enterprise", "Organization"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 600, 230));

        jLabel1.setText("Select Network: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        btnCreateOrg.setText("Add");
        add(btnCreateOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        menuNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNetworkActionPerformed(evt);
            }
        });
        add(menuNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 210, -1));

        jLabel3.setText("Select Organization: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        menuOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrganizationActionPerformed(evt);
            }
        });
        add(menuOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 210, -1));

        jLabel4.setText("Select Enterprise: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 20));

        menuEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnterpriseActionPerformed(evt);
            }
        });
        add(menuEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void menuNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNetworkActionPerformed

    private void menuOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOrganizationActionPerformed

    private void menuEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> menuEnterprise;
    private javax.swing.JComboBox<String> menuNetwork;
    private javax.swing.JComboBox<String> menuOrganization;
    // End of variables declaration//GEN-END:variables
}
