/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.GymManager;

import ui.GymMember.*;

/**
 *
 * @author yuujadz
 */
public class gymManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form memberPanel
     */
    public gymManagerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewManagementRequest = new javax.swing.JButton();
        btnViewMyMemeber = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewManagementRequest.setText("View Management Requests");
        btnViewManagementRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewManagementRequestActionPerformed(evt);
            }
        });
        add(btnViewManagementRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 40));

        btnViewMyMemeber.setText("View My Member");
        btnViewMyMemeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyMemeberActionPerformed(evt);
            }
        });
        add(btnViewMyMemeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewManagementRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewManagementRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewManagementRequestActionPerformed

    private void btnViewMyMemeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyMemeberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMyMemeberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewManagementRequest;
    private javax.swing.JButton btnViewMyMemeber;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
